name: Scraping quotidien

on:
  workflow_dispatch: {}   
  schedule:
    - cron: '0 8 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true

      - name: Run scraper
        run: docker run --rm -v ${{ github.workspace }}:/app mon-scraper:latest

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add contacts.csv
          git commit -m "Mise à jour automatisée du CSV ($(date +'%Y-%m-%d'))" || echo "Rien à commit"
          git push
